### ISSUE TITLE
demo no longer works

### ISSUE THREAD

**Issue by staabm** [github/tab-container-element#14]
https://github.github.com/tab-container-element/examples/

![grafik](https://user-images.githubusercontent.com/120441/62223481-46d00080-b3b5-11e9-9a86-6b7b88e764db.png)

tested in FF70

**Comment by koddsson** [comment]
Works fine in FF68 which is the latest stable release. Try it in another browser? It might be a issue with the beta version of FF.

**Comment by staabm** [comment]
Works on iOS, too. Maybe it does not work for a few hours after you do released when unpkg takes some time to deploy it
