### ISSUE TITLE
Use .mjs module or add "type": "module" for package.json

### ISSUE THREAD

**Issue by tarngerine** [github/tab-container-element#53]
In Sveltekit I get a warning about the package.json for this npm not being formatted correctly:

> @github/tab-container-element doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

More details in this linter:
https://publint.bjornlu.com/@github/tab-container-element@3.1.2

> "main": "dist/index.js"
> dist/index.js is written in ESM, but is interpreted as CJS. Consider using the .mjs extension, e.g. dist/index.mjs

**Comment by keithamus** [comment]
Should be resolved in later versions.
