### ISSUE TITLE
Expose `selectTab` method for programmatic selection

### ISSUE THREAD

**Issue by thetutlage** [github/tab-container-element#55]
I have a scenario in which I want to change the selected tab programmatically on the frontend. It will be great to attach the `selectTab` method on the container element to allow programmatic selection.

Happy to share more info (if required)

**Comment by keithamus** [comment]
Sounds like a good idea, maybe we should move the function into the class as a method?

**Comment by thetutlage** [comment]
Yup, we can :)

**Comment by keithamus** [comment]
If you're interested in this feature, please submit a PR if you would like it implemented!

**Comment by thetutlage** [comment]
Sure, will create a PR for the same

**Comment by stof** [comment]
Should be closed as #56 did it.
